'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Generated by CoffeeScript 2.0.3
var action, rand, roll, rollMany, rule;

rand = function rand(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
};

roll = function roll() {
  var isSpecial = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : false;

  var num;
  num = rand(1, 6);
  if (isSpecial && num === 3) {
    return '?';
  } else {
    return num;
  }
};

exports.rollMany = rollMany = function rollMany(n) {
  var i;
  return function () {
    var j, ref, results;
    results = [];
    for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      results.push(roll(i === n ? true : void 0) + '');
    }
    return results;
  }().sort().join('');
};

exports.rule = rule = function rule(matcher, actions) {
  var a, j, len;
  for (j = 0, len = actions.length; j < len; j++) {
    a = actions[j];
    a.matcher = matcher;
  }
  return { matcher: matcher, actions: actions };
};

exports.action = action = function action(type, payload) {
  return {
    "type": type,
    "payload": payload
  };
};

exports.rollMany = rollMany;
exports.rule = rule;
exports.action = action;