"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.takeTurn = undefined;

var _game = require("./game");

var _rules = require("./rules");

var _helpers = require("./helpers");

// Generated by CoffeeScript 2.0.3
var takeTurn;

exports.takeTurn = takeTurn = function takeTurn(game) {
  var act, i, j, len, len1, ref, rule;
  game.dispatch((0, _helpers.action)('roll dice', {
    times: 5
  }));
  for (i = 0, len = _rules.GAME_RULES.length; i < len; i++) {
    rule = _rules.GAME_RULES[i];
    if (rule.matcher.test(game.state.dice)) {
      ref = rule.actions;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        act = ref[j];
        game.dispatch(act);
      }
    }
  }
  return game;
};

exports.takeTurn = takeTurn;