"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.GAME_RULES = undefined;

var _helpers = require("./helpers");

// Generated by CoffeeScript 2.0.3
var GAME_RULES;

exports.GAME_RULES = GAME_RULES = [(0, _helpers.rule)(/11111/, [(0, _helpers.action)("win"), (0, _helpers.action)("quit")]), (0, _helpers.rule)(/66666/, [(0, _helpers.action)('lost'), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/22222/, [(0, _helpers.action)('points', {
  amount: 200
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/33333/, [(0, _helpers.action)('points', {
  amount: 300
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/44444/, [(0, _helpers.action)('points', {
  amount: 400
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/11(1|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 100
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/22(2|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 20
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/33(3|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 30
})]), (0, _helpers.rule)(/44(4|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 40
})]), (0, _helpers.rule)(/55(5|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 50
}), (0, _helpers.action)('quit')]), (0, _helpers.rule)(/66(6|.*\?)/, [(0, _helpers.action)('flash'), (0, _helpers.action)('points', {
  amount: 60
})]), (0, _helpers.rule)(/[15?]/, [(0, _helpers.action)('sum remaining')])];

exports.GAME_RULES = GAME_RULES;